const Sequelize = require('sequelize');

module.exports=class pdf extends Sequelize.Model{
    static init(sequelize){
        return super.init({
            csv_file_name:{
                type:Sequelize.STRING(255),
                allowNull:false,
            },
            csv_file_size:{
                type:Sequelize.INTEGER,
                allowNull:false,
            },
            csv_file_updated_at:{
                type:Sequelize.DATE,
                allowNull:false,
            },
            duration_start:{
                type:Sequelize.DATE,
                allowNull:false,
            },
            duration_end:{
                type:Sequelize.DATE,
                allowNull:false,
            },
            is_evaluated:{
                type:Sequelize.BOOLEAN,
                allowNull:true,
                defaultValue:null,
            },
            is_passed:{
                type:Sequelize.STRING(10),
                allowNull:true,
                defaultValue:null,
            },
            iteration:{
                type:Sequelize.INTEGER,
                allowNull:false,
            },
            null_ratio:{
                type:Sequelize.DOUBLE,
                allowNull:true,
            },
            num_duplicate_tuples:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            num_total_tuples:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            pars_id:{
                type:Sequelize.INTEGER,
                allowNull:false,
                primaryKey:true,
            },
            quality_score:{
                type:Sequelize.INTEGER,
                allowNull:true,
            },
            rater_id:{
                type:Sequelize.STRING(20),
                allowNull:true,
            },
            submitted_task_id:{
                type:Sequelize.INTEGER,
                allowNull:false,
            },
            submitter_id:{
                type:Sequelize.INTEGER,
                allowNull:false,
            },
            odt:{
                type:Sequelize.STRING(255),
                allowNull:false,
            }
        },{
            sequelize,
            timestamps:false,
            underscored:false,
            modelName:'pdf',
            tableName:'pars_data_seq_file',
            paranoid:false,
            charset:'utf8',
            collate:'utf8_general_ci',
        })
    }
    static associate(db){
        db.pdf.belongsTo(db.Task,{
            foreignKey:'submitted_task_id',
            targetKey:'task_id'
        });
        db.pdf.belongsTo(db.User,{
            foreignKey:'submitter_id',
            targetKey:'id'
        });
        db.pdf.belongsTo(db.User,{
            foreignKey:'rater_id',
            targetKey:'id'
        });
    }
}
